terminal:
  searchOptions: {}
  colorScheme:
    name: MaterialDark
    foreground: '#e5e5e5'
    background: '#232322'
    cursor: '#16afca'
    colors:
      - '#212121'
      - '#b7141f'
      - '#457b24'
      - '#f6981e'
      - '#134eb2'
      - '#560088'
      - '#0e717c'
      - '#efefef'
      - '#82822'
      - '#e83b3f'
      - '#7aba3a'
      - '#ffea2e'
      - '#54a4f3'
      - '#aa4dbc'
      - '#26bbd1'
      - '#d9d9d9'
  font: >-
    Fira Code Retina, Noto Sans Mono, DejaVu Sans Mono, Noto Mono, Noto Sans
    Mono CJK SC, YaHei Consolas Hybrid,Source Code Pro,Microsoft YaHei,
    Consolas, serif
  ligatures: true
  fontSize: 16
  background: colorScheme
  environment: {}
  profile: default-(wsl-/-default-distro)
  pasteOnMiddleClick: true
  copyOnSelect: true
  rightClick: paste
  altIsMeta: true
  frontend: xterm
  customColorSchemes:
    - name: Darkside
      foreground: '#bababa'
      background: '#222324'
      cursor: '#bbbbbb'
      colors:
        - '#000000'
        - '#e8341c'
        - '#68c256'
        - '#f2d42c'
        - '#1c98e8'
        - '#8e69c9'
        - '#1c98e8'
        - '#bababa'
        - '#404040'
        - '#e05a4f'
        - '#77b869'
        - '#efd64b'
        - '#387cd3'
        - '#957bbe'
        - '#3d97e2'
        - '#bababa'
    - name: MaterialDark
      foreground: '#e5e5e5'
      background: '#232322'
      cursor: '#16afca'
      colors:
        - '#212121'
        - '#b7141f'
        - '#457b24'
        - '#f6981e'
        - '#134eb2'
        - '#560088'
        - '#0e717c'
        - '#efefef'
        - '#82822'
        - '#e83b3f'
        - '#7aba3a'
        - '#ffea2e'
        - '#54a4f3'
        - '#aa4dbc'
        - '#26bbd1'
        - '#d9d9d9'
  profiles:
    - name: WSL / Ubuntu-20.04
      shell: wsl
      sessionOptions:
        command: C:\WINDOWS\system32\wsl.exe
        args:
          - '-d'
          - Ubuntu
        env:
          TERM: xterm-color
          COLORTERM: truecolor
  bell: 'off'
hotkeys:
  profile: {}
  shell: {}
  home: []
  end: []
serial: {}
appearance:
  theme: Standard
  opacity: 1
  frame: thin
  vibrancyType: fluent
  vibrancy: false
enableWelcomeTab: false
pluginBlacklist: []
enableAnalytics: false
enableAutomaticUpdates: false
